"""Model update

Revision ID: 7e3cbdd38a7c
Revises: bfa33cee6d79
Create Date: 2024-04-20 01:22:51.800895

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7e3cbdd38a7c'
down_revision = 'bfa33cee6d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###