"""Event model modification

Revision ID: 8ee288dce4fd
Revises: ab99857417b6
Create Date: 2024-04-18 19:26:54.097521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8ee288dce4fd'
down_revision = 'ab99857417b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###